sensors_point:
    sensor_plugin: occupancy_map_monitor/GaryPointCloudOctomapUpdater
    point_cloud_topic: /rs_d435/depth/color/points
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 0.5
    filtered_cloud_topic: ""
